-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDe+kaE8as5cfcMY3
IpvRPviNnfBhIG+65tha7fxGADqgCgYIKoZIzj0DAQehRANCAAQD8U47VrG4n25E
d3w4kzWo3peVv+DsYPLkKeWT+7mdhpSv5N/nW6WpNkEDBGtbfTs/Q+CFp3dvEAZz
mv6otwXG
-----END PRIVATE KEY-----